/**
 * @author Youngjae Lee
 * @version 2022-02-13
 *
 * description: DTO class
 */

package dmit2015.youngjaelee.assignment03.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.io.Serializable;


/**
 * The persistent class for the OscarReviews database table.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
public class OscarReviewDto implements Serializable {

    @Id                 // This is the primary key field
    // This primary key field is generated by the database
    private Long id;

    @Column(nullable = false, length = 25)
    @NotBlank(message = "Category is required")
    @Size(min=1, max=25, message = "size must be between 1 and 25")
    private String category;

    @Column(nullable = false, length = 25)
    @NotBlank(message = "Nominee is required")
    @Size(min=1, max=25, message = "size must be between 1 and 25")
    private String nominee;

    @Column(nullable = false, length = 100)
    @NotBlank(message = "You must type review")
    @Size(min=1, max=100, message = "size must be between 1 and 100")
    private String review;

    @Column(nullable = false, length = 30)
    @NotBlank(message = "Username is required")
    @Size(min=1, max=30, message = "size must be between 1 and 30")
    private String username;

    @Version
    private Integer version;

}